'use client'

import { useState } from 'react'
import { X, Lock, Check, Download, Loader2, Copy } from 'lucide-react'
import { Button } from '@/components/ui/button'
import html2canvas from 'html2canvas'

interface ExportModalProps {
  isOpen: boolean
  onClose: () => void
  userPlan: 'free' | 'starter' | 'pro' | 'agency'
  onUpgrade: () => void
  generatedHTML?: string
}

type ExportOption = {
  id: string
  name: string
  description: string
  available: boolean
}

export function ExportModal({ isOpen, onClose, userPlan, onUpgrade, generatedHTML = '' }: ExportModalProps) {
  const [selectedExports, setSelectedExports] = useState<string[]>([])
  const [isExporting, setIsExporting] = useState(false)
  const [isCopied, setIsCopied] = useState(false)

  if (!isOpen) return null

  const getExportOptions = (): ExportOption[] => {
    const allOptions: ExportOption[] = [
      {
        id: 'html-single',
        name: 'Single-file HTML',
        description: 'Complete page in one file',
        available: userPlan !== 'free'
      },
      {
        id: 'html-css-zip',
        name: 'HTML + CSS (ZIP)',
        description: 'Structured project files',
        available: userPlan === 'pro' || userPlan === 'agency'
      },
      {
        id: 'react-nextjs',
        name: 'React / Next.js',
        description: 'Component-based export',
        available: userPlan === 'pro' || userPlan === 'agency'
      },
      {
        id: 'image-export',
        name: 'Image exports',
        description: 'Desktop + mobile screenshots',
        available: userPlan === 'pro' || userPlan === 'agency'
      },
      {
        id: 'client-handoff',
        name: 'Client handoff export',
        description: 'Production-ready package',
        available: userPlan === 'agency'
      }
    ]

    return allOptions
  }

  const exportOptions = getExportOptions()
  const canMultiSelect = userPlan === 'agency'

  const handleExportSelect = (optionId: string, available: boolean) => {
    if (!available) return

    if (canMultiSelect) {
      setSelectedExports(prev =>
        prev.includes(optionId)
          ? prev.filter(id => id !== optionId)
          : [...prev, optionId]
      )
    } else {
      setSelectedExports([optionId])
    }
  }

  const downloadFile = (filename: string, content: string, mimeType: string = 'text/html') => {
    const blob = new Blob([content], { type: mimeType })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = filename
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  const copyToClipboard = async () => {
    const htmlContent = generateHTMLExport()
    try {
      await navigator.clipboard.writeText(htmlContent)
      setIsCopied(true)
      setTimeout(() => setIsCopied(false), 2000)
    } catch (err) {
      console.error('Failed to copy:', err)
    }
  }

  const generateHTMLExport = () => {
    // Use the actual generated HTML if available, otherwise return a placeholder
    if (generatedHTML && generatedHTML.trim()) {
      return generatedHTML
    }

    // Fallback placeholder if no HTML is generated yet
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Landing Page - Generated by Vorg</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #333;
    }
    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 0 20px;
    }
    header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 80px 0;
      text-align: center;
    }
    h1 {
      font-size: 48px;
      margin-bottom: 20px;
      font-weight: 700;
    }
    .cta-button {
      display: inline-block;
      background: white;
      color: #667eea;
      padding: 14px 36px;
      border-radius: 24px;
      text-decoration: none;
      font-weight: 600;
      margin-top: 20px;
      transition: transform 0.2s;
    }
    .cta-button:hover {
      transform: scale(1.05);
    }
    .features {
      padding: 80px 0;
      text-align: center;
    }
    .features h2 {
      font-size: 36px;
      margin-bottom: 60px;
    }
    .feature-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
      gap: 40px;
    }
    .feature-card {
      padding: 30px;
      border-radius: 12px;
      box-shadow: 0 4px 6px rgba(0,0,0,0.1);
    }
    footer {
      background: #2d3748;
      color: white;
      text-align: center;
      padding: 40px 0;
    }
  </style>
</head>
<body>
  <header>
    <div class="container">
      <h1>Your Landing Page</h1>
      <p>Generated with Vorg AI</p>
      <a href="#" class="cta-button">Get Started</a>
    </div>
  </header>

  <section class="features">
    <div class="container">
      <h2>Features</h2>
      <div class="feature-grid">
        <div class="feature-card">
          <h3>Fast & Modern</h3>
          <p>Built with the latest web technologies</p>
        </div>
        <div class="feature-card">
          <h3>Responsive</h3>
          <p>Looks great on all devices</p>
        </div>
        <div class="feature-card">
          <h3>Customizable</h3>
          <p>Easy to modify and extend</p>
        </div>
      </div>
    </div>
  </section>

  <footer>
    <div class="container">
      <p>&copy; 2025 Generated with Vorg</p>
    </div>
  </footer>
</body>
</html>`
  }

  const extractCSS = (html: string) => {
    // Extract CSS from <style> tags in the HTML
    const styleMatch = html.match(/<style[^>]*>([\s\S]*?)<\/style>/i)
    if (styleMatch && styleMatch[1]) {
      return styleMatch[1].trim()
    }
    return ''
  }

  const extractHTMLBody = (html: string) => {
    // Extract content between <body> tags
    const bodyMatch = html.match(/<body[^>]*>([\s\S]*?)<\/body>/i)
    if (bodyMatch && bodyMatch[1]) {
      return bodyMatch[1].trim()
    }
    return html
  }

  const generateReactComponent = () => {
    // Use the actual generated HTML if available
    if (generatedHTML && generatedHTML.trim()) {
      const bodyContent = extractHTMLBody(generatedHTML)

      return `import React from 'react';
import './LandingPage.css'; // Import the CSS file

export default function LandingPage() {
  return (
    <div dangerouslySetInnerHTML={{ __html: \`${bodyContent.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\` }} />
  );
}
`
    }

    // Fallback if no HTML is generated
    return `import React from 'react';

export default function LandingPage() {
  return (
    <div>
      <header style={{
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        color: 'white',
        padding: '80px 0',
        textAlign: 'center'
      }}>
        <h1>Your Landing Page</h1>
        <p>Generated with Vorg AI</p>
      </header>
    </div>
  );
}
`
  }

  const captureScreenshots = async () => {
    // Create temporary containers for desktop and mobile views
    const desktopContainer = document.createElement('div')
    const mobileContainer = document.createElement('div')

    // Style desktop container (1920px width)
    desktopContainer.style.position = 'fixed'
    desktopContainer.style.left = '-9999px'
    desktopContainer.style.top = '0'
    desktopContainer.style.width = '1920px'
    desktopContainer.style.background = 'white'
    desktopContainer.innerHTML = generatedHTML || ''

    // Style mobile container (375px width - iPhone size)
    mobileContainer.style.position = 'fixed'
    mobileContainer.style.left = '-9999px'
    mobileContainer.style.top = '0'
    mobileContainer.style.width = '375px'
    mobileContainer.style.background = 'white'
    mobileContainer.innerHTML = generatedHTML || ''

    document.body.appendChild(desktopContainer)
    document.body.appendChild(mobileContainer)

    try {
      // Capture desktop screenshot
      const desktopCanvas = await html2canvas(desktopContainer, {
        width: 1920,
        windowWidth: 1920,
        scale: 1,
        useCORS: true,
        allowTaint: true,
        backgroundColor: '#ffffff'
      })

      // Capture mobile screenshot
      const mobileCanvas = await html2canvas(mobileContainer, {
        width: 375,
        windowWidth: 375,
        scale: 2,
        useCORS: true,
        allowTaint: true,
        backgroundColor: '#ffffff'
      })

      // Convert canvases to blobs and download
      desktopCanvas.toBlob((blob) => {
        if (blob) {
          const url = URL.createObjectURL(blob)
          const link = document.createElement('a')
          link.href = url
          link.download = 'landing-page-desktop.png'
          document.body.appendChild(link)
          link.click()
          document.body.removeChild(link)
          URL.revokeObjectURL(url)
        }
      })

      setTimeout(() => {
        mobileCanvas.toBlob((blob) => {
          if (blob) {
            const url = URL.createObjectURL(blob)
            const link = document.createElement('a')
            link.href = url
            link.download = 'landing-page-mobile.png'
            document.body.appendChild(link)
            link.click()
            document.body.removeChild(link)
            URL.revokeObjectURL(url)
          }
        })
      }, 300)
    } finally {
      // Clean up temporary containers
      document.body.removeChild(desktopContainer)
      document.body.removeChild(mobileContainer)
    }
  }

  const handleExport = async () => {
    if (selectedExports.length === 0) return

    setIsExporting(true)

    // Simulate export process
    await new Promise(resolve => setTimeout(resolve, 1500))

    // Generate and download files based on selection
    for (const exportId of selectedExports) {
      switch (exportId) {
        case 'html-single':
          downloadFile('landing-page.html', generateHTMLExport(), 'text/html')
          break

        case 'html-css-zip':
          // Extract CSS and create separate HTML and CSS files from actual generated HTML
          const extractedCSS = extractCSS(generatedHTML || '')
          const bodyContent = extractHTMLBody(generatedHTML || '')

          const htmlWithExternalCSS = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Landing Page - Generated by Vorg</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
${bodyContent}
</body>
</html>`

          downloadFile('index.html', htmlWithExternalCSS, 'text/html')
          setTimeout(() => downloadFile('styles.css', extractedCSS, 'text/css'), 300)
          break

        case 'react-nextjs':
          // Download React component and its CSS file
          downloadFile('LandingPage.jsx', generateReactComponent(), 'text/javascript')
          setTimeout(() => {
            const cssContent = extractCSS(generatedHTML || '')
            downloadFile('LandingPage.css', cssContent, 'text/css')
          }, 300)
          break

        case 'image-export':
          // Capture screenshots of the generated HTML in both desktop and mobile views
          await captureScreenshots()
          break

        case 'client-handoff':
          // Download a comprehensive package
          downloadFile('landing-page-full.html', generateHTMLExport(), 'text/html')
          setTimeout(() => {
            const readme = `# Landing Page - Client Handoff

## Files Included
- landing-page-full.html - Complete landing page
- All assets are embedded for easy deployment

## Deployment Instructions
1. Upload the HTML file to your web server
2. Or open directly in a browser for preview
3. Customize colors and content as needed

## Technical Details
- Fully responsive design
- Modern CSS with flexbox/grid
- No external dependencies
- SEO-friendly markup

Generated with Vorg - https://vorg.com
`
            downloadFile('README.md', readme, 'text/markdown')
          }, 300)
          break
      }
    }

    setIsExporting(false)
    setSelectedExports([])
    onClose()
  }

  const getModalContent = () => {
    // Free plan
    if (userPlan === 'free') {
      return (
        <>
          <div className="space-y-3 mb-6">
            {exportOptions.slice(0, 3).map((option) => (
              <div
                key={option.id}
                className="relative flex items-center justify-between p-4 rounded-lg border border-white/10 bg-white/[0.02] opacity-50"
              >
                <div className="flex items-center gap-3">
                  <Lock className="w-4 h-4 text-gray-500" />
                  <div>
                    <p className="text-sm font-medium text-[hsl(var(--text-primary))]">{option.name}</p>
                    <p className="text-xs text-[hsl(var(--text-secondary))]">{option.description}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className="text-center mb-6">
            <p className="text-sm text-[hsl(var(--text-secondary))]">
              Exporting is available on paid plans.
            </p>
          </div>

          <div className="flex flex-col gap-3">
            <Button
              onClick={onUpgrade}
              className="w-full h-11 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium"
            >
              Upgrade to Export
            </Button>
            <Button
              onClick={onClose}
              className="w-full h-11 bg-white/10 hover:bg-white/15 text-[hsl(var(--text-primary))] rounded-lg font-medium border border-white/10"
            >
              Continue previewing
            </Button>
          </div>
        </>
      )
    }

    // Starter plan
    if (userPlan === 'starter') {
      return (
        <>
          <div className="space-y-3 mb-6">
            {exportOptions.map((option) => (
              <button
                key={option.id}
                onClick={() => handleExportSelect(option.id, option.available)}
                disabled={!option.available}
                className={`w-full flex items-center justify-between p-4 rounded-lg border transition-all ${
                  option.available
                    ? selectedExports.includes(option.id)
                      ? 'border-blue-500 bg-blue-600/10'
                      : 'border-white/10 bg-white/[0.02] hover:border-white/20 hover:bg-white/[0.04]'
                    : 'border-white/10 bg-white/[0.02] opacity-50 cursor-not-allowed'
                }`}
              >
                <div className="flex items-center gap-3">
                  {option.available ? (
                    selectedExports.includes(option.id) ? (
                      <Check className="w-4 h-4 text-blue-500" />
                    ) : (
                      <div className="w-4 h-4 rounded-full border-2 border-white/20" />
                    )
                  ) : (
                    <Lock className="w-4 h-4 text-gray-500" />
                  )}
                  <div className="text-left">
                    <p className="text-sm font-medium text-[hsl(var(--text-primary))]">{option.name}</p>
                    <p className="text-xs text-[hsl(var(--text-secondary))]">{option.description}</p>
                  </div>
                </div>
              </button>
            ))}
          </div>

          <div className="flex flex-col gap-3">
            <div className="flex gap-3">
              <Button
                onClick={handleExport}
                disabled={selectedExports.length === 0 || isExporting}
                className="flex-1 h-11 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                {isExporting ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    Exporting…
                  </>
                ) : (
                  <>
                    <Download className="w-4 h-4" />
                    Download
                  </>
                )}
              </Button>
              <Button
                onClick={copyToClipboard}
                disabled={selectedExports.length === 0 || isExporting}
                className="flex-1 h-11 bg-white/10 hover:bg-white/15 text-[hsl(var(--text-primary))] rounded-lg font-medium border border-white/10 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                {isCopied ? (
                  <>
                    <Check className="w-4 h-4" />
                    Copied!
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4" />
                    Copy Code
                  </>
                )}
              </Button>
            </div>
            <Button
              onClick={onUpgrade}
              className="w-full h-11 bg-white/10 hover:bg-white/15 text-[hsl(var(--text-primary))] rounded-lg font-medium border border-white/10"
            >
              Upgrade for more export options
            </Button>
          </div>
        </>
      )
    }

    // Pro plan
    if (userPlan === 'pro') {
      return (
        <>
          <div className="space-y-3 mb-4">
            {exportOptions.map((option) => (
              <button
                key={option.id}
                onClick={() => handleExportSelect(option.id, option.available)}
                disabled={!option.available}
                className={`w-full flex items-center justify-between p-4 rounded-lg border transition-all ${
                  option.available
                    ? selectedExports.includes(option.id)
                      ? 'border-blue-500 bg-blue-600/10'
                      : 'border-white/10 bg-white/[0.02] hover:border-white/20 hover:bg-white/[0.04]'
                    : 'border-white/10 bg-white/[0.02] opacity-50 cursor-not-allowed'
                }`}
              >
                <div className="flex items-center gap-3">
                  {option.available ? (
                    selectedExports.includes(option.id) ? (
                      <Check className="w-4 h-4 text-blue-500" />
                    ) : (
                      <div className="w-4 h-4 rounded-full border-2 border-white/20" />
                    )
                  ) : (
                    <Lock className="w-4 h-4 text-gray-500" />
                  )}
                  <div className="text-left">
                    <p className="text-sm font-medium text-[hsl(var(--text-primary))]">{option.name}</p>
                    <p className="text-xs text-[hsl(var(--text-secondary))]">{option.description}</p>
                  </div>
                </div>
              </button>
            ))}
          </div>

          <p className="text-xs text-[hsl(var(--text-secondary))] text-center mb-6">
            Optimized for production use.
          </p>

          <div className="flex gap-3">
            <Button
              onClick={handleExport}
              disabled={selectedExports.length === 0 || isExporting}
              className="flex-1 h-11 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              {isExporting ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Exporting…
                </>
              ) : (
                <>
                  <Download className="w-4 h-4" />
                  Download
                </>
              )}
            </Button>
            <Button
              onClick={copyToClipboard}
              disabled={selectedExports.length === 0 || isExporting}
              className="flex-1 h-11 bg-white/10 hover:bg-white/15 text-[hsl(var(--text-primary))] rounded-lg font-medium border border-white/10 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              {isCopied ? (
                <>
                  <Check className="w-4 h-4" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  Copy Code
                </>
              )}
            </Button>
          </div>
        </>
      )
    }

    // Agency plan
    if (userPlan === 'agency') {
      return (
        <>
          <div className="space-y-3 mb-4">
            {exportOptions.map((option) => (
              <button
                key={option.id}
                onClick={() => handleExportSelect(option.id, option.available)}
                className={`w-full flex items-center justify-between p-4 rounded-lg border transition-all ${
                  selectedExports.includes(option.id)
                    ? 'border-blue-500 bg-blue-600/10'
                    : 'border-white/10 bg-white/[0.02] hover:border-white/20 hover:bg-white/[0.04]'
                }`}
              >
                <div className="flex items-center gap-3">
                  {selectedExports.includes(option.id) ? (
                    <Check className="w-4 h-4 text-blue-500" />
                  ) : (
                    <div className="w-4 h-4 rounded-full border-2 border-white/20" />
                  )}
                  <div className="text-left">
                    <p className="text-sm font-medium text-[hsl(var(--text-primary))]">{option.name}</p>
                    <p className="text-xs text-[hsl(var(--text-secondary))]">{option.description}</p>
                  </div>
                </div>
              </button>
            ))}
          </div>

          <p className="text-xs text-[hsl(var(--text-secondary))] text-center mb-6">
            Select multiple export formats.
          </p>

          <div className="flex gap-3">
            <Button
              onClick={handleExport}
              disabled={selectedExports.length === 0 || isExporting}
              className="flex-1 h-11 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              {isExporting ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Exporting…
                </>
              ) : (
                <>
                  <Download className="w-4 h-4" />
                  Export All
                </>
              )}
            </Button>
            <Button
              onClick={copyToClipboard}
              disabled={selectedExports.length === 0 || isExporting}
              className="flex-1 h-11 bg-white/10 hover:bg-white/15 text-[hsl(var(--text-primary))] rounded-lg font-medium border border-white/10 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              {isCopied ? (
                <>
                  <Check className="w-4 h-4" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  Copy Code
                </>
              )}
            </Button>
          </div>
        </>
      )
    }
  }

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/50 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Modal */}
      <div className="relative w-full max-w-md bg-[hsl(var(--bg-secondary))] rounded-2xl shadow-2xl border border-white/10">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-white/10">
          <h2 className="text-lg font-semibold text-[hsl(var(--text-primary))]">Export your landing page</h2>
          <button
            onClick={onClose}
            className="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-white/5 transition-colors"
          >
            <X className="w-5 h-5 text-[hsl(var(--text-secondary))]" />
          </button>
        </div>

        {/* Content */}
        <div className="px-6 py-6">
          {getModalContent()}
        </div>
      </div>
    </div>
  )
}
